### PR TITLE
add LED scan for XMOS startKIT for beginners

### PR DESCRIPTION
**Pull request by funkyguy4000**
This program blinks each of the startKITs onboard LEDs individually to give new users an idea on how to address them.
This is meant to be similar to the Arduinos Blink sketch.

### CODE REVIEW

**Comment by funkyguy4000** [comment]
Oh and this also added the full startKIT port mappings header file which maps all of the ports to their respective labelled functions on the headers on the startKIT as well as all of the slices offered by XMOS

**Comment by ghost** [comment]
Looks good but you have committed the .build_Debug directory as well which isn't needed. Could you possibly resubmit without that directory?

**Comment by funkyguy4000** [comment]
There we go.  I actually got a chance before tonight.
If you would like me to make a whole new pull request, that would be totally fine.

**Comment by ghost** [comment]
No need to make a new pull request. I have rebased your commit though since it seems better not to have the build files in the history at all.

Should be merged in now.

**Pull request closed without merging**
